export default {
    add: 'insert',
    confirm: '',
    detail: 'detail',
    search: 'query',
    clear: '',
    export: 'output',
    import: 'batchimport',
    template: '',
    save: 'save',
    cancel: 'abandon',
    update: 'update',
    delete: 'delete',
    pbmsubmit: 'submit',
    pbmcancle: 'unsubmit',
    pbmapprove: '',
    appoint: '',
    printpreview: '',
    printdesign: '',
    upload: '',
    reupload: '',
    download: '',
    addRow: '',
    delRow: '',
    copyRow: 'copy',
    max: '',
    min: '',
    copyToEnd: '',
    organizationChat: '',
    enable: 'enable',
    disabled: 'disable',
    next: '',
    previous: '',
    first: '',
    last: '',
    //defined:'defined',//自定义
}

